// uni-app/src/components/runner/RouteMapSheet.vue
<template>
  <SheetModal :show="show" title="赛道补给地图" @close="$emit('close')">
    <text class="hint">{{ categoryHint }}</text>
    <view v-if="loadError" class="err">{{ loadError }}</view>
    <scroll-view v-if="showSwitcher" scroll-x class="routes">
      <text
        v-for="r in bundle.routes"
        :key="r.id"
        class="route-chip"
        :class="{ active: r.id === activeRouteId }"
        @tap="setRoute(r.id)"
      >
        {{ r.name }}{{ r.distanceKm != null ? ` · ${r.distanceKm}km` : '' }}
      </text>
    </scroll-view>
    <view v-if="activeLine" class="meta">
      <text>当前：{{ activeLine.name }}</text>
      <text v-if="activeLine.distanceKm != null"> · 全程约 {{ activeLine.distanceKm }} km</text>
      <text> · 赛道 {{ pathReady ? '已配置' : '未绘制' }} · 打点 {{ listItems.length }} 个</text>
    </view>
    <RouteMapView
      :line="activeLine"
      :amap-cfg="amapCfg"
      :marker-heat="markerHeat"
      :selected-marker-id="selectedMarkerId"
      :loading="loading"
      :visible="show"
      @select-marker="selectedMarkerId = $event"
    />
    <text class="list-title">补给站 / 打卡点列表（点击可在地图上定位）</text>
    <RouteMapMarkerList
      :line="activeLine"
      :loading="loading"
      :selected-marker-id="selectedMarkerId"
      :marker-heat="markerHeat"
      @select="onListSelect"
    />
    <view class="map-legend">
      <view class="legend-item"><view class="dot dot-start" /><text>起点</text></view>
      <view class="legend-item"><view class="dot dot-finish" /><text>终点</text></view>
      <view class="legend-item"><view class="dot dot-aid" /><text>补给</text></view>
      <view class="legend-item"><view class="dot dot-medical" /><text>医疗</text></view>
      <view class="legend-item"><view class="dot dot-cp" /><text>检查点</text></view>
      <view class="legend-item"><view class="dot dot-warn" /><text>咨询偏多</text></view>
      <view class="legend-item"><view class="dot dot-hot" /><text>热点预警</text></view>
    </view>
  </SheetModal>
</template>

<script setup>
import { ref, watch, computed, onUnmounted } from 'vue'
import SheetModal from './SheetModal.vue'
import RouteMapView from './RouteMapView.vue'
import RouteMapMarkerList from './RouteMapMarkerList.vue'
import {
  fetchAmapClientConfig,
  fetchEventRouteMapBundle,
  fetchMapPoiHeat,
  fetchProfile,
} from '@/utils/runner-api.js'
import { findLine, resolveLineForCategory, categoryLabel } from '@/utils/route-map.js'
import { buildRouteMapListItems } from '@/utils/route-map-list.js'

const props = defineProps({
  show: Boolean,
  eventGuid: String,
  runnerCategory: String,
})
defineEmits(['close'])

const loading = ref(false)
const loadError = ref(null)
const bundle = ref(null)
const activeRouteId = ref('')
const profileCategory = ref(props.runnerCategory)
const selectedMarkerId = ref(null)
const markerHeat = ref({})
const amapCfg = ref({ enabled: false })
let heatTimer = null

watch(
  () => props.runnerCategory,
  (c) => {
    profileCategory.value = c
  },
)

async function loadHeat() {
  const guid = props.eventGuid
  const routeId = activeRouteId.value
  if (!guid || !routeId) return
  try {
    const rows = await fetchMapPoiHeat(guid, routeId)
    const map = {}
    for (const r of rows) map[r.markerId] = r.heatLevel
    markerHeat.value = map
  } catch {
    markerHeat.value = {}
  }
}

function clearHeatPoll() {
  if (heatTimer) {
    clearInterval(heatTimer)
    heatTimer = null
  }
}

function startHeatPoll() {
  clearHeatPoll()
  loadHeat()
  heatTimer = setInterval(loadHeat, 15000)
}

watch(
  () => [props.show, props.eventGuid],
  async ([open, guid]) => {
    if (!open || !guid) {
      clearHeatPoll()
      return
    }
    loading.value = true
    loadError.value = null
    selectedMarkerId.value = null
    try {
      let category = props.runnerCategory
      if (!category) {
        try {
          const p = await fetchProfile()
          category = p.category
          if (category) profileCategory.value = category
        } catch {
          /* visitor */
        }
      }
      const [cfg, b] = await Promise.all([
        fetchAmapClientConfig().catch(() => ({ enabled: false })),
        fetchEventRouteMapBundle(guid),
      ])
      amapCfg.value = {
        enabled: cfg.enabled,
        apiKey: cfg.apiKey,
        securityJsCode: cfg.securityJsCode,
      }
      bundle.value = b
      const auto = resolveLineForCategory(b, category)
      activeRouteId.value = auto?.id ?? b.defaultRouteId ?? b.routes[0]?.id ?? ''
    } catch (e) {
      bundle.value = null
      loadError.value = e?.message || '加载赛道数据失败'
    } finally {
      loading.value = false
    }
  },
)

watch(
  () => [props.show, props.eventGuid, activeRouteId.value],
  ([open, guid, routeId]) => {
    clearHeatPoll()
    if (!open || !guid || !routeId) return
    startHeatPoll()
  },
)

onUnmounted(clearHeatPoll)

const activeLine = computed(() => {
  if (!bundle.value) return null
  return findLine(bundle.value, activeRouteId.value) ?? bundle.value.routes[0] ?? null
})

const listItems = computed(() => buildRouteMapListItems(activeLine.value))
const showSwitcher = computed(() => (bundle.value?.routes?.length ?? 0) > 1)
const pathReady = computed(() => (activeLine.value?.path?.length ?? 0) >= 2)

const categoryHint = computed(() =>
  profileCategory.value
    ? `已按组别「${categoryLabel(bundle.value?.categories ?? [], profileCategory.value)}」匹配线路，也可手动切换`
    : '选择参赛线路查看赛道路线与补给、打卡点',
)

function setRoute(id) {
  activeRouteId.value = id
  selectedMarkerId.value = null
}

function onListSelect(id) {
  selectedMarkerId.value = id
}
</script>

<style scoped>
.hint {
  font-size: 24rpx;
  color: var(--secondary-text);
  margin-bottom: 16rpx;
  display: block;
  line-height: 1.45;
}
.err {
  background: #fffbeb;
  border: 1px solid #fde68a;
  padding: 16rpx;
  border-radius: 12rpx;
  font-size: 24rpx;
  color: #92400e;
  margin-bottom: 16rpx;
}
.routes {
  white-space: nowrap;
  margin-bottom: 16rpx;
}
.route-chip {
  display: inline-block;
  margin-right: 12rpx;
  padding: 10rpx 20rpx;
  font-size: 24rpx;
  border: 1px solid var(--secondary-border);
  border-radius: 999rpx;
  color: var(--secondary-text);
  background: #fff;
}
.route-chip.active {
  background: var(--primary);
  color: #fff;
  border-color: var(--primary);
}
.meta {
  font-size: 22rpx;
  color: var(--secondary-text);
  margin-bottom: 12rpx;
  line-height: 1.5;
}
.list-title {
  font-size: 22rpx;
  color: #94a3b8;
  margin: 24rpx 0 12rpx;
  display: block;
}
.map-legend {
  display: flex;
  flex-wrap: wrap;
  gap: 16rpx 24rpx;
  margin-top: 24rpx;
  font-size: 20rpx;
  color: #94a3b8;
}
.legend-item {
  display: flex;
  align-items: center;
  gap: 8rpx;
}
.dot {
  width: 16rpx;
  height: 16rpx;
  border-radius: 50%;
}
.dot-start {
  background: #10b981;
}
.dot-finish {
  background: #7c3aed;
}
.dot-aid {
  background: var(--primary);
}
.dot-medical {
  background: #ef4444;
}
.dot-cp {
  background: #f59e0b;
}
.dot-warn {
  background: #f97316;
  box-shadow: 0 0 0 2rpx #fdba74;
}
.dot-hot {
  background: #ef4444;
  animation: heat-pulse 1s ease infinite;
}
@keyframes heat-pulse {
  50% {
    opacity: 0.6;
  }
}
</style>

// src/components/modals/RouteMapSheet.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { SheetModal } from "@/components/modals/SheetModal";
import { AmapRouteMapView } from "@/components/map/AmapRouteMapView";
import { RouteMapMarkerList } from "@/components/map/RouteMapMarkerList";
import {
  fetchAmapClientConfig,
  fetchEventRouteMapBundle,
  fetchMapPoiHeat,
  fetchProfile,
} from "@/api/runner-api";
import type { PoiHeatLevel } from "@/lib/route-map-markers";
import type { AmapClientConfig } from "@/lib/amap-loader";
import { buildRouteMapListItems } from "@/lib/route-map-list";
import {
  categoryLabel,
  findLine,
  resolveLineForCategory,
  type EventRouteLine,
  type EventRouteMapBundle,
} from "@/types/route-map";

interface Props {
  open: boolean;
  eventGuid: string;
  /** 选手组别，绑定身份后由 profile 传入 */
  runnerCategory?: string;
  onClose: () => void;
}

export function RouteMapSheet({ open, eventGuid, runnerCategory, onClose }: Props) {
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [bundle, setBundle] = useState<EventRouteMapBundle | null>(null);
  const [amapCfg, setAmapCfg] = useState<AmapClientConfig | null>(null);
  const [activeRouteId, setActiveRouteId] = useState<string>("");
  const [profileCategory, setProfileCategory] = useState<string | undefined>(runnerCategory);
  const [selectedMarkerId, setSelectedMarkerId] = useState<string | null>(null);
  const [markerHeat, setMarkerHeat] = useState<Record<string, PoiHeatLevel>>({});

  useEffect(() => {
    setProfileCategory(runnerCategory);
  }, [runnerCategory]);

  const loadRouteData = useCallback(async () => {
    if (!eventGuid) return;
    setLoading(true);
    setLoadError(null);
    setSelectedMarkerId(null);
    try {
      let category = runnerCategory;
      if (!category) {
        try {
          const p = await fetchProfile();
          category = p.category;
          if (category) setProfileCategory(category);
        } catch {
          /* 访客无 profile */
        }
      }

      const [cfg, b] = await Promise.all([
        fetchAmapClientConfig(),
        fetchEventRouteMapBundle(eventGuid),
      ]);
      setAmapCfg({
        enabled: cfg.enabled,
        apiKey: cfg.apiKey,
        securityJsCode: cfg.securityJsCode,
      });
      setBundle(b);
      const auto = resolveLineForCategory(b, category);
      setActiveRouteId(auto?.id ?? b.defaultRouteId ?? b.routes[0]?.id ?? "");
    } catch (e) {
      setBundle(null);
      setAmapCfg({ enabled: false });
      setLoadError(e instanceof Error ? e.message : "加载赛道数据失败");
    } finally {
      setLoading(false);
    }
  }, [eventGuid, runnerCategory]);

  useEffect(() => {
    if (!open || !eventGuid) return;
    void loadRouteData();
  }, [open, eventGuid, loadRouteData]);

  useEffect(() => {
    if (!open || !eventGuid || !activeRouteId) return;
    let cancelled = false;
    const loadHeat = async () => {
      try {
        const rows = await fetchMapPoiHeat(eventGuid, activeRouteId);
        if (cancelled) return;
        const map: Record<string, PoiHeatLevel> = {};
        for (const r of rows) {
          map[r.markerId] = r.heatLevel;
        }
        setMarkerHeat(map);
      } catch {
        if (!cancelled) setMarkerHeat({});
      }
    };
    void loadHeat();
    const iv = window.setInterval(loadHeat, 15000);
    return () => {
      cancelled = true;
      clearInterval(iv);
    };
  }, [open, eventGuid, activeRouteId]);

  const activeLine: EventRouteLine | null = useMemo(() => {
    if (!bundle) return null;
    return findLine(bundle, activeRouteId) ?? bundle.routes[0] ?? null;
  }, [bundle, activeRouteId]);

  const listItems = useMemo(() => buildRouteMapListItems(activeLine), [activeLine]);
  const showRouteSwitcher = (bundle?.routes.length ?? 0) > 1;

  const onRouteChange = (routeId: string) => {
    setActiveRouteId(routeId);
    setSelectedMarkerId(null);
  };

  return (
    <SheetModal open={open} title="赛道补给地图" onClose={onClose}>
      <p className="text-xs text-slate-500 mb-3">
        {profileCategory
          ? `已按组别「${categoryLabel(bundle?.categories ?? [], profileCategory)}」匹配线路，也可手动切换`
          : "选择参赛线路查看赛道路线与补给、打卡点"}
      </p>

      {loadError && (
        <p className="text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 mb-3">
          {loadError}
        </p>
      )}

      {showRouteSwitcher && bundle && (
        <div className="flex flex-wrap gap-2 mb-3">
          {bundle.routes.map((r) => (
            <button
              key={r.id}
              type="button"
              className={`text-xs px-3 py-1.5 rounded-full border font-medium ${
                r.id === activeRouteId
                  ? "bg-primary text-white border-primary"
                  : "bg-white text-slate-600 border-slate-200"
              }`}
              onClick={() => onRouteChange(r.id)}
            >
              {r.name}
              {r.distanceKm != null ? ` · ${r.distanceKm}km` : ""}
            </button>
          ))}
        </div>
      )}

      {activeLine && (
        <div className="flex flex-wrap gap-3 text-2xs text-slate-500 mb-2">
          <span>当前：{activeLine.name}</span>
          {activeLine.distanceKm != null && (
            <span>全程约 {activeLine.distanceKm} km</span>
          )}
          <span>
            赛道 {activeLine.path.length >= 2 ? "已配置" : "未绘制"} · 打点 {listItems.length} 个
          </span>
        </div>
      )}

      <AmapRouteMapView
        line={activeLine}
        amapCfg={amapCfg}
        parentLoading={loading}
        selectedMarkerId={selectedMarkerId}
        onMarkerSelect={setSelectedMarkerId}
        markerHeat={markerHeat}
      />

      <div className="mt-4">
        <p className="text-2xs text-slate-400 mb-2">
          补给站 / 打卡点列表（点击可在地图上定位）
        </p>
        <RouteMapMarkerList
          line={activeLine}
          loading={loading}
          selectedMarkerId={selectedMarkerId}
          onSelect={setSelectedMarkerId}
          markerHeat={markerHeat}
        />
      </div>

      <div className="flex flex-wrap gap-2 mt-3 text-[10px] text-slate-400">
        <span className="inline-flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-emerald-500" /> 起点
        </span>
        <span className="inline-flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-violet-500" /> 终点
        </span>
        <span className="inline-flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-primary" /> 补给
        </span>
        <span className="inline-flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-red-500" /> 医疗
        </span>
        <span className="inline-flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-amber-500" /> 检查点
        </span>
        <span className="inline-flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-orange-500 ring-1 ring-orange-300" /> 咨询偏多
        </span>
        <span className="inline-flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-red-500 animate-pulse" /> 热点预警
        </span>
      </div>
    </SheetModal>
  );
}
