// uni-app/src/components/runner/ChatPanel.vue
<template>
  <view
    class="chat-section"
    :class="{
      'chat-section--maximized': maximized,
      'chat-section--mp': useMpScrollFill,
    }"
  >
    <view class="chat-section-header">
      <view class="chat-header-title-wrap">
        <text class="chat-title">AI 赛事助手</text>
      </view>
      <view class="header-right">
        <view
          v-if="showMaximize"
          class="chat-max-btn"
          role="button"
          :aria-label="maximized ? '恢复聊天窗口大小' : '最大化聊天窗口'"
          @tap="$emit('toggle-maximize')"
        >
          <!-- #ifdef MP-WEIXIN -->
          <text class="chat-max-btn-text">{{ maximized ? '收起' : '全屏' }}</text>
          <!-- #endif -->
          <!-- #ifndef MP-WEIXIN -->
          <ChatMaximizeIcon :maximized="maximized" />
          <!-- #endif -->
        </view>
        <!-- #ifndef MP-WEIXIN -->
        <text class="chat-status" :class="{ ok: chatEnabled }">{{ statusLabelShort }}</text>
        <!-- #endif -->
      </view>
    </view>

    <view class="chat-messages-area">
      <scroll-view
        class="chat-messages"
        scroll-y
        :style="messagesScrollStyle"
        :scroll-into-view="scrollIntoView"
        scroll-with-animation
        @scroll="onScroll"
      >
        <view v-for="m in messages" :key="m.id" :id="'msg-' + m.id">
          <ChatMessageItem
            :message="m"
            :runner="runner"
            :greeting="m.id === 'greet' ? greeting : undefined"
          />
        </view>
        <view v-if="thinking" class="chat-thinking">
          <view class="chat-thinking-dot" />
          <view class="chat-thinking-dot" style="animation-delay: 0.15s" />
          <view class="chat-thinking-dot" style="animation-delay: 0.3s" />
          <text>对麦正在思考</text>
        </view>
        <view v-if="chatError" class="chat-error">{{ chatError }}</view>
        <view id="msg-bottom" style="height: 2px" />
      </scroll-view>
      <text v-if="showScrollBtn" class="chat-scroll-fab" @tap="scrollBottom">↓ 回到底部</text>
    </view>

    <view class="chat-input-footer">
      <scroll-view v-if="prompts.length" class="chat-prompts" scroll-x>
        <text
          v-for="(p, i) in prompts"
          :key="i"
          class="prompt-pill"
          :class="{ disabled: thinking || !chatEnabled }"
          @tap="onPrompt(p)"
        >
          {{ p }}
        </text>
      </scroll-view>
      <ChatInput
        :disabled="thinking || !chatEnabled"
        :locale="locale"
        @send-text="sendTextMessage"
        @voice-file="onVoiceFile"
      />
    </view>
  </view>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import ChatInput from './ChatInput.vue'
import ChatMessageItem from './ChatMessageItem.vue'
import ChatMaximizeIcon from '@/components/icons/ChatMaximizeIcon.vue'
import {
  sendChat,
  transcribeSpeech,
  fetchChatInbox,
  fetchChatHistory,
} from '@/utils/runner-api.js'
import { mapHistoryToChatMessages } from '@/utils/chat-history.js'
import { resolveQuickPrompts } from '@/utils/event-phase.js'
import {
  subscribeRunnerChatHumanReply,
  subscribeRunnerChatSocketOpen,
  getRunnerChatSocketState,
  subscribeRunnerChatSocketState,
} from '@/utils/runner-chat-ws.js'
import { ApiError } from '@/utils/api.js'
import { t } from '@/utils/i18n.js'
import { isMpWeixinPlatform } from '@/utils/mp-layout.js'

const props = defineProps({
  phase: { type: String, default: 'pre' },
  greeting: { type: String, default: '' },
  runner: { type: Object, default: () => ({}) },
  chatEnabled: Boolean,
  chatDisabledHint: String,
  offlineHint: String,
  h5QuickQuestions: Object,
  inboxPollEnabled: Boolean,
  historyEnabled: Boolean,
  runnerId: String,
  maximized: Boolean,
  showMaximize: { type: Boolean, default: true },
  locale: { type: String, default: 'zh' },
  /** 小程序 scroll-view 高度(px)，由 useMpRunnerLayout 测算 */
  messagesScrollPx: { type: Number, default: 0 },
})
defineEmits(['toggle-maximize'])

const messages = ref([
  { id: 'greet', role: 'assistant', text: '', createdAt: Date.now() },
])
const thinking = ref(false)
const chatError = ref(null)
const scrollIntoView = ref('')
const showScrollBtn = ref(false)
const conversationId = ref(undefined)
const deliveredInboxIds = new Set()
const wsOpen = ref(false)
let inboxTimer = null
let unsubWs = null
let unsubOpen = null
let unsubState = null
const nearBottom = ref(true)

const useMpScrollFill = isMpWeixinPlatform()

const messagesScrollStyle = computed(() => {
  if (useMpScrollFill && props.maximized) {
    return {
      height: '100%',
      width: '100%',
      minHeight: '0',
      boxSizing: 'border-box',
    }
  }
  if (useMpScrollFill && props.messagesScrollPx > 0) {
    return {
      height: `${props.messagesScrollPx}px`,
      width: '100%',
      boxSizing: 'border-box',
    }
  }
  return { height: '100%', width: '100%', boxSizing: 'border-box' }
})

watch(
  () => props.messagesScrollPx,
  () => {
    if (nearBottom.value) scrollBottom()
  },
)

defineExpose({ remeasure: () => {} })

const prompts = computed(() =>
  resolveQuickPrompts(props.phase, props.h5QuickQuestions),
)

const statusLabel = computed(() => {
  if (props.chatEnabled) return '已连接 AI'
  return props.chatDisabledHint || props.offlineHint || t(props.locale, 'aiDisabled')
})

/** 标题栏优先保证最大化按钮可见 */
const statusLabelShort = computed(() => {
  if (props.chatEnabled) return '已连接'
  const full = statusLabel.value
  if (!full) return ''
  return full.length > 8 ? `${full.slice(0, 8)}…` : full
})

function uid() {
  return `m-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
}

function scrollBottom() {
  nearBottom.value = true
  showScrollBtn.value = false
  scrollIntoView.value = ''
  setTimeout(() => {
    scrollIntoView.value = 'msg-bottom'
  }, 30)
}

function onScroll(e) {
  const detail = e.detail
  const dist = detail.scrollHeight - detail.scrollTop - (detail.deltaY || 400)
  nearBottom.value = dist < 80
  showScrollBtn.value = !nearBottom.value
}

async function streamText(streamId, fullText) {
  for (let i = 1; i <= fullText.length; i++) {
    await new Promise((r) => setTimeout(r, 16))
    const slice = fullText.slice(0, i)
    messages.value = messages.value.map((m) =>
      m.id === streamId ? { ...m, text: slice, streaming: i < fullText.length } : m,
    )
  }
}

async function appendStaff(items) {
  for (const item of items) {
    if (!item.id || !item.text?.trim() || deliveredInboxIds.has(item.id)) continue
    deliveredInboxIds.add(item.id)
    messages.value.push({
      id: item.id,
      role: 'staff',
      text: item.text.trim(),
      createdAt: item.createdAt ?? Date.now(),
    })
  }
  if (nearBottom.value) scrollBottom()
}

async function drainInbox() {
  try {
    const inbox = await fetchChatInbox()
    if (!inbox?.length) return
    const fresh = inbox.filter(
      (m) => m.id && m.text?.trim() && !deliveredInboxIds.has(m.id),
    )
    if (fresh.length) await appendStaff(fresh)
  } catch {
    /* 静默 */
  }
}

async function loadHistory() {
  if (!props.historyEnabled || !props.runnerId || props.runnerId === 'visitor') return
  try {
    const res = await fetchChatHistory()
    if (res.conversationId) conversationId.value = res.conversationId
    const loaded = mapHistoryToChatMessages(res.messages ?? [])
    if (!loaded.length) return
    for (const m of loaded) {
      if (m.id.startsWith('hist-')) deliveredInboxIds.add(m.id)
    }
    const greet = messages.value.find((m) => m.id === 'greet')
    const byId = new Map()
    for (const m of messages.value) {
      if (m.id !== 'greet') byId.set(m.id, m)
    }
    for (const m of loaded) byId.set(m.id, m)
    const merged = [...byId.values()].sort((a, b) => (a.createdAt ?? 0) - (b.createdAt ?? 0))
    messages.value = greet ? [greet, ...merged] : merged
    scrollBottom()
  } catch {
    /* 静默 */
  }
}

async function appendReply(answer) {
  const fullText = answer?.trim()
  if (!fullText) {
    chatError.value = '助手未返回内容'
    return
  }
  const streamId = uid()
  messages.value.push({
    id: streamId,
    role: 'assistant',
    text: '',
    streaming: true,
    createdAt: Date.now(),
  })
  await streamText(streamId, fullText)
}

async function sendQueryToAi(text, voiceMeta) {
  if (thinking.value) return
  if (!props.chatEnabled) {
    chatError.value = props.chatDisabledHint || props.offlineHint || t(props.locale, 'aiDisabled')
    return
  }
  thinking.value = true
  chatError.value = null
  try {
    const res = await sendChat({
      query: text,
      conversationId: conversationId.value,
      ...(voiceMeta
        ? { inputSource: 'voice', voiceDurationMs: voiceMeta.durationMs }
        : {}),
    })
    if (res.conversationId) conversationId.value = res.conversationId
    await appendReply(res.answer)
    if (nearBottom.value) scrollBottom()
  } catch (e) {
    const msg = e instanceof ApiError ? e.message : '对话请求失败'
    if (/conversation not exists/i.test(msg)) conversationId.value = undefined
    chatError.value = msg
  } finally {
    thinking.value = false
  }
}

async function sendTextMessage(text) {
  if (thinking.value) return
  messages.value.push({ id: uid(), role: 'user', text, createdAt: Date.now() })
  scrollBottom()
  await sendQueryToAi(text)
}

async function onVoiceFile({ filePath, blob, durationMs }) {
  if (thinking.value || !props.chatEnabled) return
  const msgId = uid()
  messages.value.push({
    id: msgId,
    role: 'user',
    voiceStatus: 'transcribing',
    createdAt: Date.now(),
  })
  scrollBottom()
  thinking.value = true
  try {
    const res = await transcribeSpeech(blob || filePath)
    const text = res.text?.trim()
    if (!text) {
      messages.value = messages.value.map((m) =>
        m.id === msgId ? { ...m, voiceStatus: 'failed' } : m,
      )
      chatError.value = '未识别到有效语音'
      return
    }
    messages.value = messages.value.map((m) =>
      m.id === msgId
        ? { ...m, voiceStatus: 'done', text, inputSource: 'voice' }
        : m,
    )
    await sendQueryToAi(text, { durationMs: durationMs || res.durationMs })
  } catch (e) {
    messages.value = messages.value.map((m) =>
      m.id === msgId ? { ...m, voiceStatus: 'failed' } : m,
    )
    chatError.value = e instanceof ApiError ? e.message : '语音识别失败'
  } finally {
    thinking.value = false
  }
}

function onPrompt(p) {
  if (thinking.value || !props.chatEnabled) return
  sendTextMessage(p)
}

function setupInboxPoll() {
  if (inboxTimer) clearInterval(inboxTimer)
  inboxTimer = null
  if (!props.inboxPollEnabled) return
  const ms = wsOpen.value ? 15000 : 800
  inboxTimer = setInterval(drainInbox, ms)
}

function teardownInbox() {
  if (unsubWs) {
    unsubWs()
    unsubWs = null
  }
  if (unsubOpen) {
    unsubOpen()
    unsubOpen = null
  }
  if (unsubState) {
    unsubState()
    unsubState = null
  }
  if (inboxTimer) {
    clearInterval(inboxTimer)
    inboxTimer = null
  }
}

watch(
  () => props.inboxPollEnabled,
  (on) => {
    teardownInbox()
    if (!on) return
    unsubWs = subscribeRunnerChatHumanReply((m) => appendStaff([m]))
    unsubOpen = subscribeRunnerChatSocketOpen(() => drainInbox())
    unsubState = subscribeRunnerChatSocketState(() => {
      wsOpen.value = getRunnerChatSocketState() === 'open'
      setupInboxPoll()
    })
    wsOpen.value = getRunnerChatSocketState() === 'open'
    drainInbox()
    setupInboxPoll()
  },
  { immediate: true },
)

watch(
  () => [messages.value.length, thinking.value],
  () => {
    if (nearBottom.value) scrollBottom()
  },
)

onMounted(() => {
  loadHistory()
})

onUnmounted(() => {
  teardownInbox()
})
</script>

<style scoped>
.chat-header-title-wrap {
  flex: 1;
  min-width: 0;
  margin-right: 12rpx;
}
.header-right {
  display: flex;
  align-items: center;
  gap: 12rpx;
  flex-shrink: 0;
  margin-left: auto;
  min-width: 88rpx;
}
.chat-max-btn {
  flex-shrink: 0;
}

/* #ifdef MP-WEIXIN */
.chat-section--mp.chat-section--maximized {
  height: 100%;
  min-height: 0;
}

.chat-section--mp .chat-section-header,
.chat-section--mp .chat-input-footer {
  flex-shrink: 0;
}

.chat-section--mp .chat-messages-area {
  flex: 1 1 auto;
  min-height: 0;
  overflow: hidden;
}
/* #endif */
</style>

// src/components/ChatPanel.tsx
import { useCallback, useEffect, useRef, useState } from "react";

import { ChatInput } from "@/components/ChatInput";
import { ScrollToBottomButton } from "@/components/ScrollToBottomButton";
import { ChatMessageItem } from "@/components/ChatMessageItem";
import { ChatSessionTime } from "@/components/ChatSessionTime";
import { SuggestedPrompts } from "@/components/SuggestedPrompts";
import { fetchChatHistory, fetchChatInbox, sendChat, transcribeSpeech } from "@/api/runner-api";
import { mapHistoryToChatMessages } from "@/lib/chat-history";
import type { VoiceMessagePayload } from "@/components/ChatInput";
import { ApiError } from "@/lib/api-client";
import { clampVoiceDurationMs } from "@/lib/voice-message";
import { useRunnerChatSocketState } from "@/hooks/useRunnerChatSocketState";
import { subscribeRunnerChatHumanReply, subscribeRunnerChatSocketOpen } from "@/lib/runner-chat-ws";
import { resolveQuickPrompts } from "@/lib/h5-quick-questions";
import type { H5QuickQuestions } from "@/api/runner-api";
import type { ChatMessage, H5Phase, RunnerProfile } from "@/types";

interface Props {
  phase: H5Phase;
  runner: RunnerProfile;
  greeting: string;
  /** 已连接后端且 AI 可用 */
  chatEnabled: boolean;
  chatDisabledHint?: string;
  h5QuickQuestions?: H5QuickQuestions | null;
  /** 已绑定身份时可轮询人工回复 */
  inboxPollEnabled?: boolean;
  /** 已绑定身份时加载服务端聊天记录 */
  historyEnabled?: boolean;
}

/** WebSocket 未连通时快速拉取 Redis 收件箱 */
const INBOX_FAST_POLL_MS = 800;
/** WebSocket 已连通时的低频兜底 */
const INBOX_BACKUP_POLL_MS = 15000;

function uid() {
  return `m-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
}

function now() {
  return Date.now();
}

function initialSessionTime() {
  const d = new Date();
  d.setHours(6, 15, 0, 0);
  return d;
}

async function streamText(
  streamId: string,
  fullText: string,
  setMessages: React.Dispatch<React.SetStateAction<ChatMessage[]>>,
) {
  for (let i = 1; i <= fullText.length; i++) {
    await new Promise((r) => setTimeout(r, 20));
    const slice = fullText.slice(0, i);
    setMessages((prev) =>
      prev.map((m) =>
        m.id === streamId ? { ...m, text: slice, streaming: i < fullText.length } : m,
      ),
    );
  }
}

export function ChatPanel({
  phase,
  runner,
  greeting,
  chatEnabled,
  chatDisabledHint,
  h5QuickQuestions,
  inboxPollEnabled = false,
  historyEnabled = false,
}: Props) {
  const [messages, setMessages] = useState<ChatMessage[]>([
    { id: "greet", role: "assistant", text: "", createdAt: initialSessionTime().getTime() },
  ]);
  const [sessionAt, setSessionAt] = useState(initialSessionTime);
  const [thinking, setThinking] = useState(false);
  const [chatError, setChatError] = useState<string | null>(null);
  const conversationIdRef = useRef<string | undefined>();
  const deliveredInboxIdsRef = useRef<Set<string>>(new Set());
  const audioObjectUrlsRef = useRef<Set<string>>(new Set());
  const bottomRef = useRef<HTMLDivElement>(null);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const nearBottomRef = useRef(true);
  const [showScrollToBottom, setShowScrollToBottom] = useState(false);
  const wsState = useRunnerChatSocketState();
  const wsOpen = wsState === "open";
  const prompts = resolveQuickPrompts(phase, h5QuickQuestions);

  const touchSession = useCallback(() => {
    setSessionAt(new Date());
  }, []);

  const isNearBottom = useCallback(() => {
    const el = scrollContainerRef.current;
    if (!el) return true;
    return el.scrollHeight - el.scrollTop - el.clientHeight < 72;
  }, []);

  const scrollBottom = useCallback((behavior: ScrollBehavior = "smooth") => {
    bottomRef.current?.scrollIntoView({ behavior });
    nearBottomRef.current = true;
    setShowScrollToBottom(false);
  }, []);

  const onMessagesScroll = useCallback(() => {
    const near = isNearBottom();
    nearBottomRef.current = near;
    setShowScrollToBottom(!near);
  }, [isNearBottom]);

  useEffect(() => {
    if (nearBottomRef.current) {
      scrollBottom(messages.length <= 2 ? "auto" : "smooth");
    }
  }, [messages, thinking, scrollBottom]);

  const appendStaffMessages = useCallback(
    async (items: { id: string; text: string; createdAt?: number }[]) => {
      for (const item of items) {
        if (deliveredInboxIdsRef.current.has(item.id)) continue;
        deliveredInboxIdsRef.current.add(item.id);
        const fullText = item.text?.trim() ?? "";
        if (!fullText) continue;
        setMessages((prev) => [
          ...prev,
          {
            id: item.id,
            role: "staff",
            text: fullText,
            createdAt: item.createdAt ?? now(),
          },
        ]);
        touchSession();
      }
    },
    [touchSession],
  );

  const drainInboxRef = useRef<() => Promise<void>>(async () => {});

  drainInboxRef.current = async () => {
    try {
      const inbox = await fetchChatInbox();
      if (!inbox?.length) return;
      const fresh = inbox.filter(
        (m) => m.id && m.text?.trim() && !deliveredInboxIdsRef.current.has(m.id),
      );
      if (fresh.length) await appendStaffMessages(fresh);
    } catch {
      /* 静默 */
    }
  };

  useEffect(() => {
    if (!historyEnabled || !runner.id || runner.id === "visitor") return;

    let cancelled = false;
    (async () => {
      try {
        const res = await fetchChatHistory();
        if (cancelled) return;
        if (res.conversationId) conversationIdRef.current = res.conversationId;

        const loaded = mapHistoryToChatMessages(res.messages ?? []);
        if (loaded.length === 0) return;

        for (const m of loaded) {
          if (m.id.startsWith("hist-")) {
            deliveredInboxIdsRef.current.add(m.id);
          }
        }

        setMessages((prev) => {
          const greet = prev.find((m) => m.id === "greet");
          const byId = new Map<string, ChatMessage>();
          for (const m of prev) {
            if (m.id === "greet") continue;
            byId.set(m.id, m);
          }
          for (const m of loaded) {
            byId.set(m.id, m);
          }
          const merged = [...byId.values()].sort(
            (a, b) => (a.createdAt ?? 0) - (b.createdAt ?? 0),
          );
          return greet ? [greet, ...merged] : merged;
        });

        const firstTs = loaded.find((m) => m.createdAt)?.createdAt;
        if (firstTs) setSessionAt(new Date(firstTs));
        requestAnimationFrame(() => scrollBottom("auto"));
      } catch (e) {
        if (!cancelled) {
          console.warn("[ChatPanel] 加载聊天记录失败", e);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [historyEnabled, runner.id]);

  /** WebSocket 订阅：勿把 wsOpen 放入 deps，否则 open 时会卸载重连导致资源耗尽 */
  useEffect(() => {
    if (!inboxPollEnabled) return;

    const onHumanReply = (m: { id: string; text: string; createdAt?: number }) => {
      void appendStaffMessages([m]);
    };

    const unsubscribeWs = subscribeRunnerChatHumanReply(onHumanReply);
    const unsubscribeOpen = subscribeRunnerChatSocketOpen(() => {
      void drainInboxRef.current();
    });
    void drainInboxRef.current();

    return () => {
      unsubscribeOpen();
      unsubscribeWs();
    };
  }, [inboxPollEnabled, appendStaffMessages]);

  /** 收件箱兜底轮询：与 WS 生命周期分离 */
  useEffect(() => {
    if (!inboxPollEnabled) return;

    const pollMs = wsOpen ? INBOX_BACKUP_POLL_MS : INBOX_FAST_POLL_MS;
    const timer = setInterval(() => void drainInboxRef.current(), pollMs);
    return () => clearInterval(timer);
  }, [inboxPollEnabled, wsOpen]);

  const appendReply = useCallback(
    async (reply: Omit<ChatMessage, "id" | "role" | "createdAt">) => {
      if (reply.cardType) {
        setMessages((prev) => [
          ...prev,
          { id: uid(), role: "assistant", ...reply, createdAt: now() },
        ]);
        touchSession();
        return;
      }

      const fullText = reply.text?.trim() ?? "";
      if (!fullText) {
        setChatError("助手未返回内容");
        return;
      }

      const streamId = uid();
      setMessages((prev) => [
        ...prev,
        { id: streamId, role: "assistant", text: "", streaming: true, createdAt: now() },
      ]);
      await streamText(streamId, fullText, setMessages);
      touchSession();
    },
    [touchSession],
  );

  const sendQueryToAi = useCallback(
    async (text: string, voiceMeta?: { durationMs: number }) => {
      if (thinking) return;

      if (!chatEnabled) {
        setChatError(chatDisabledHint ?? "AI 对话不可用，请检查后端服务");
        return;
      }

      setThinking(true);
      setChatError(null);

      try {
        const res = await sendChat({
          query: text,
          conversationId: conversationIdRef.current,
          ...(voiceMeta
            ? { inputSource: "voice" as const, voiceDurationMs: voiceMeta.durationMs }
            : {}),
        });
        if (res.conversationId) conversationIdRef.current = res.conversationId;

        const answer = res.answer?.trim();
        if (!answer) {
          setChatError("助手未返回内容，请稍后重试");
          return;
        }

        await appendReply({ text: answer });
      } catch (e) {
        const msg = e instanceof ApiError ? e.message : "对话请求失败，请稍后重试";
        if (/conversation not exists/i.test(msg)) {
          conversationIdRef.current = undefined;
        }
        setChatError(msg);
      } finally {
        setThinking(false);
      }
    },
    [thinking, chatEnabled, chatDisabledHint, appendReply],
  );

  const sendTextMessage = useCallback(
    async (text: string) => {
      if (thinking) return;
      const ts = now();
      setMessages((prev) => [...prev, { id: uid(), role: "user", text, createdAt: ts }]);
      touchSession();
      await sendQueryToAi(text);
    },
    [thinking, touchSession, sendQueryToAi],
  );

  const handleVoiceMessage = useCallback(
    async ({ blob, durationMs: rawDurationMs }: VoiceMessagePayload) => {
      if (thinking) return;

      const durationMs = clampVoiceDurationMs(rawDurationMs);
      nearBottomRef.current = true;
      const msgId = uid();
      const audioUrl = URL.createObjectURL(blob);
      audioObjectUrlsRef.current.add(audioUrl);
      const ts = now();

      setMessages((prev) => [
        ...prev,
        {
          id: msgId,
          role: "user",
          audioUrl,
          audioDurationMs: durationMs,
          voiceStatus: "transcribing",
          createdAt: ts,
        },
      ]);
      touchSession();

      if (!chatEnabled) {
        setMessages((prev) =>
          prev.map((m) => (m.id === msgId ? { ...m, voiceStatus: "failed" } : m)),
        );
        setChatError(chatDisabledHint ?? "AI 对话不可用");
        return;
      }

      try {
        const res = await transcribeSpeech(blob);
        const text = res.text?.trim();
        if (!text) {
          setMessages((prev) =>
            prev.map((m) => (m.id === msgId ? { ...m, voiceStatus: "failed" } : m)),
          );
          setChatError("未识别到有效语音，请重试");
          return;
        }

        setMessages((prev) =>
          prev.map((m) =>
            m.id === msgId
              ? {
                  ...m,
                  voiceStatus: "done",
                  text,
                  inputSource: "voice",
                }
              : m,
          ),
        );
        await sendQueryToAi(text, { durationMs });
      } catch (e) {
        setMessages((prev) =>
          prev.map((m) => (m.id === msgId ? { ...m, voiceStatus: "failed" } : m)),
        );
        const msg = e instanceof ApiError ? e.message : "语音识别失败";
        setChatError(msg);
      }
    },
    [thinking, touchSession, chatEnabled, chatDisabledHint, sendQueryToAi],
  );

  useEffect(() => {
    const urls = audioObjectUrlsRef.current;
    return () => {
      urls.forEach((url) => URL.revokeObjectURL(url));
      urls.clear();
    };
  }, []);

  const statusLabel = chatEnabled
    ? "已连接 AI"
    : (chatDisabledHint ?? "AI 不可用");

  return (
    <section className="chat-section">
      <div className="flex items-center justify-between border-b border-secondary-border/80 bg-white px-3 py-2.5">
        <h2 className="text-sm font-bold text-ink">AI 赛事助手</h2>
        <span className={`text-2xs font-semibold ${chatEnabled ? "text-primary" : "text-amber-600"}`}>
          {statusLabel}
        </span>
      </div>

      <div className="chat-messages-area bg-[var(--chat-bg)]">
        <div
          ref={scrollContainerRef}
          onScroll={onMessagesScroll}
          className="chat-messages-canvas absolute inset-0 overflow-y-auto overscroll-y-contain px-3 pb-1"
        >
          <ChatSessionTime at={sessionAt} />
          <div className="space-y-3 py-2">
            {messages.map((m) => (
              <ChatMessageItem
                key={m.id}
                message={m}
                runner={runner}
                greeting={m.id === "greet" ? greeting : undefined}
              />
            ))}
            {thinking && (
              <div className="flex items-center gap-2 pr-16 text-sm font-medium text-secondary">
                <span className="inline-flex gap-1">
                  <span className="w-2 h-2 rounded-full bg-primary animate-bounce" />
                  <span className="w-2 h-2 rounded-full bg-primary animate-bounce [animation-delay:0.15s]" />
                  <span className="w-2 h-2 rounded-full bg-primary animate-bounce [animation-delay:0.3s]" />
                </span>
                对麦正在思考
              </div>
            )}
            {chatError && (
              <p className="mx-3 text-2xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-2 py-1.5">
                {chatError}
              </p>
            )}
            <div ref={bottomRef} className="h-2" />
          </div>
        </div>
        <ScrollToBottomButton
          visible={showScrollToBottom}
          onClick={() => scrollBottom("smooth")}
        />
      </div>

      <div className="shrink-0 border-t border-secondary-border bg-white shadow-[0_-4px_12px_rgba(15,23,42,0.04)]">
        <SuggestedPrompts
          prompts={prompts}
          onSelect={sendTextMessage}
          disabled={thinking || !chatEnabled}
        />
        <ChatInput
          onSendText={sendTextMessage}
          onVoiceMessage={handleVoiceMessage}
          disabled={thinking || !chatEnabled}
        />
      </div>
    </section>
  );
}
