// src/components/AiAvatar.tsx
/** 对麦 AI 头像 · 赛事红橙渐变 */
export function AiAvatar({ size = "sm" }: { size?: "sm" | "md" }) {
  const dim = size === "md" ? "h-7 w-7 text-xs" : "h-6 w-6 text-[10px]";
  return (
    <span
      className={`${dim} flex shrink-0 items-center justify-center rounded-full font-bold text-white`}
      style={{
        background: "linear-gradient(145deg, #ef4444 0%, var(--primary) 100%)",
        boxShadow: "0 2px 6px rgba(239, 68, 68, 0.35)",
      }}
      aria-hidden
    >
      麦
    </span>
  );
}

// uni-app/src/components/runner/AiAvatar.vue
<template>
  <view class="ai-avatar" :class="size">
    <text>麦</text>
  </view>
</template>

<script setup>
defineProps({
  size: { type: String, default: 'sm' },
})
</script>

<style scoped>
.ai-avatar {
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  font-weight: 700;
  color: #fff;
  flex-shrink: 0;
  background: linear-gradient(145deg, #ef4444 0%, var(--primary) 100%);
  box-shadow: 0 4rpx 12rpx rgba(239, 68, 68, 0.35);
}
.ai-avatar.sm {
  width: 48rpx;
  height: 48rpx;
  font-size: 20rpx;
}
.ai-avatar.md {
  width: 56rpx;
  height: 56rpx;
  font-size: 24rpx;
}
</style>
