// src/components/ChatMessageItem.tsx
import { BibPickupCard } from "@/components/cards/BibPickupCard";
import { SupplyStationCard } from "@/components/cards/SupplyStationCard";
import { AiAvatar } from "@/components/AiAvatar";
import { GreetingMessage } from "@/components/GreetingMessage";
import { useTypewriter } from "@/hooks/useTypewriter";
import { FormattedChatText } from "@/lib/format-chat-markdown";
import type { ChatMessage, RunnerProfile } from "@/types";

interface Props {
  message: ChatMessage;
  runner?: RunnerProfile;
  greeting?: string;
}

export function ChatMessageItem({ message, runner, greeting }: Props) {
  const isUser = message.role === "user";
  const streamText = useTypewriter(message.text ?? "", !!message.streaming);

  if (message.id === "greet" && runner) {
    return <GreetingMessage runner={runner} greeting={greeting} />;
  }

  if (isUser) {
    return (
      <div className="flex justify-end px-3 pr-14">
        <div className="user-bubble max-w-[85%] rounded-2xl rounded-br-md px-3.5 py-2.5 text-[15px] text-white font-medium">
          {message.text}
        </div>
      </div>
    );
  }

  return (
    <div className="flex justify-start px-3 pr-14">
      <div className="max-w-[92%] space-y-2">
        <div className="flex items-center gap-1.5 text-2xs text-secondary px-1">
          <AiAvatar />
          对麦智能
        </div>
        {message.cardType === "supply" && message.supply && (
          <SupplyStationCard data={message.supply} />
        )}
        {message.cardType === "bib" && message.bib && <BibPickupCard data={message.bib} />}
        {message.text && (
          <div className="ai-bubble rounded-2xl rounded-bl-md px-3.5 py-2.5 text-[15px] text-ink font-medium">
            <FormattedChatText text={message.streaming ? streamText : message.text} />
            {message.streaming && streamText.length < (message.text?.length ?? 0) && (
              <span className="inline-block w-1.5 h-4 ml-0.5 bg-primary animate-pulse align-middle" />
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// uni-app/src/components/runner/ChatMessageItem.vue
<template>
  <GreetingMessage
    v-if="message.id === 'greet'"
    :runner="runner"
    :greeting="greeting"
  />
  <view v-else-if="message.role === 'user' && message.text" class="chat-row-user">
    <view class="user-bubble">
      <text class="user-text">{{ message.text }}</text>
    </view>
    <UserAvatar />
  </view>
  <view v-else-if="message.role === 'staff'" class="chat-row-assistant">
    <view class="staff-bubble">
      <text>{{ message.text }}</text>
    </view>
  </view>
  <view v-else-if="message.role === 'assistant'" class="chat-row-assistant">
    <view class="assistant-col">
      <view v-if="message.streaming" class="assistant-label">
        <AiAvatar />
        <text class="label-text">对麦智能</text>
      </view>
      <view class="ai-bubble">
        <text>{{ message.text }}</text>
        <text v-if="message.streaming" class="cursor">|</text>
      </view>
    </view>
  </view>
</template>

<script setup>
import GreetingMessage from './GreetingMessage.vue'
import AiAvatar from './AiAvatar.vue'
import UserAvatar from './UserAvatar.vue'

defineProps({
  message: Object,
  runner: Object,
  greeting: String,
})
</script>

<style scoped>
.user-text {
  text-align: right;
}
.assistant-col {
  max-width: 88%;
}
.assistant-label {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-bottom: 8rpx;
  font-size: 22rpx;
  color: var(--secondary-text);
}
.cursor {
  color: var(--primary);
  margin-left: 4rpx;
}
</style>
