// src/components/ChatFooter.tsx
import { t } from "@/lib/i18n";
import type { Locale } from "@/lib/i18n";

interface Props {
  footerSupport?: string;
  hidePoweredBy?: boolean;
  locale?: Locale;
  onOpenLegal?: (type: "privacy" | "terms") => void;
}

export function ChatFooter({
  footerSupport,
  hidePoweredBy = false,
  locale = "zh",
  onOpenLegal,
}: Props) {
  const hasSupport = Boolean(footerSupport?.trim());
  const showPowered = !hidePoweredBy;
  const showLegal = Boolean(onOpenLegal);
  if (!hasSupport && !showPowered && !showLegal) {
    return null;
  }

  return (
    <footer className="runner-app-footer border-t border-secondary-border/80 px-3 py-1 text-center text-2xs text-secondary safe-bottom">
      {hasSupport ? (
        <span className="block text-sm font-semibold text-red-600">{footerSupport}</span>
      ) : null}
      {showPowered ? <span className="text-secondary">{t(locale, "poweredBy")}</span> : null}
      {showLegal && (
        <span className="mt-0.5 flex justify-center gap-3 text-secondary">
          <button type="button" className="underline" onClick={() => onOpenLegal!("privacy")}>
            {locale === "en" ? "Privacy" : "隐私政策"}
          </button>
          <button type="button" className="underline" onClick={() => onOpenLegal!("terms")}>
            {locale === "en" ? "Terms" : "用户协议"}
          </button>
        </span>
      )}
    </footer>
  );
}

// uni-app/src/components/runner/ChatFooter.vue
<template>
  <view v-if="visible" class="runner-footer">
    <text v-if="footerSupport" class="footer-support">{{ footerSupport }}</text>
    <text v-if="!hidePoweredBy">{{ poweredLabel }}</text>
    <view v-if="showLegal" class="legal-row">
      <text class="legal-link" @tap="$emit('open-legal', 'privacy')">{{ privacyLabel }}</text>
      <text class="legal-link" @tap="$emit('open-legal', 'terms')">{{ termsLabel }}</text>
    </view>
  </view>
</template>

<script setup>
import { computed } from 'vue'
import { t } from '@/utils/i18n.js'

const props = defineProps({
  footerSupport: String,
  hidePoweredBy: Boolean,
  locale: { type: String, default: 'zh' },
  showLegal: { type: Boolean, default: true },
})
defineEmits(['open-legal'])

const visible = computed(
  () =>
    !!props.footerSupport?.trim() ||
    !props.hidePoweredBy ||
    props.showLegal,
)
const poweredLabel = computed(() => t(props.locale, 'poweredBy'))
const privacyLabel = computed(() => (props.locale === 'en' ? 'Privacy' : '隐私政策'))
const termsLabel = computed(() => (props.locale === 'en' ? 'Terms' : '用户协议'))
</script>

<style scoped>
.legal-row {
  display: flex;
  justify-content: center;
  gap: 32rpx;
  margin-top: 8rpx;
}
.legal-link {
  text-decoration: underline;
}
</style>
