// src/components/GreetingMessage.tsx
import { AiAvatar } from "@/components/AiAvatar";
import { FormattedChatText } from "@/lib/format-chat-markdown";
import type { RunnerProfile } from "@/types";

interface Props {
  runner: RunnerProfile;
  /** 后端返回的问候语，优先展示 */
  greeting?: string;
}

export function GreetingMessage({ runner, greeting }: Props) {
  const hasProfile = Boolean(runner?.name?.trim() && runner?.bib?.trim());
  const bibNum = runner?.bib?.replace(/^[A-Z]/i, "") ?? "";

  return (
    <div className="chat-row-assistant">
      <div className="max-w-[88%]">
        <div className="mb-1 flex items-center gap-1.5 px-0.5 text-2xs font-medium text-secondary">
          <AiAvatar />
          对麦智能
        </div>
        <div className="ai-bubble rounded-2xl rounded-bl-md px-3.5 py-3 text-[15px] font-medium text-ink">
          {greeting ? (
            <FormattedChatText text={greeting} />
          ) : hasProfile ? (
            <>
              Hi <span className="font-bold text-primary-dark">{runner!.name}</span>，你是{" "}
              <span className="font-bold text-primary">
                {runner!.zone} {bibNum} 号
              </span>
              选手，请于 <span className="font-bold text-primary">{runner!.checkInBefore}</span> 前到达{" "}
              <span className="font-bold text-primary-dark">{runner!.zone}</span> 检录。
            </>
          ) : (
            <>
              你好，我是 <span className="font-bold text-primary-dark">对麦赛事助手</span>
              。完赛后可问我领物、补给、交通等问题；验证参赛身份后可查看个人参赛信息。
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// uni-app/src/components/runner/GreetingMessage.vue
<template>
  <view class="chat-row-assistant">
    <view class="assistant-col">
      <view class="assistant-label">
        <AiAvatar />
        <text class="label-text">对麦智能</text>
      </view>
      <view class="ai-bubble">
        <text v-if="greeting" class="bubble-text">{{ greeting }}</text>
        <text v-else-if="hasProfile" class="bubble-text">
          Hi <text class="text-primary-dark">{{ runner.name }}</text>，你是
          <text class="text-primary">{{ runner.zone }} {{ bibNum }} 号</text>
          选手，请于 <text class="text-primary">{{ runner.checkInBefore }}</text> 前到达
          <text class="text-primary-dark">{{ runner.zone }}</text> 检录。
        </text>
        <text v-else class="bubble-text">
          你好，我是 <text class="text-primary-dark">对麦赛事助手</text>。完赛后可问我领物、补给、交通等问题；验证参赛身份后可查看个人参赛信息。
        </text>
      </view>
    </view>
  </view>
</template>

<script setup>
import { computed } from 'vue'
import AiAvatar from './AiAvatar.vue'

const props = defineProps({
  runner: Object,
  greeting: String,
})

const hasProfile = computed(
  () => Boolean(props.runner?.name?.trim() && props.runner?.bib?.trim()),
)
const bibNum = computed(() => props.runner?.bib?.replace(/^[A-Z]/i, '') ?? '')
</script>

<style scoped>
.assistant-col {
  max-width: 88%;
}
.assistant-label {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-bottom: 8rpx;
  font-size: 22rpx;
  font-weight: 500;
  color: var(--secondary-text);
}
.label-text {
  font-size: 22rpx;
}
.bubble-text {
  font-size: 30rpx;
  line-height: 1.5;
}
</style>
