// src/components/modals/PickupGuideSheet.tsx
import { useEffect, useState } from "react";
import { SheetModal } from "@/components/modals/SheetModal";
import { fetchEventShuttleConfig } from "@/api/runner-api";
import { isPickupVisible } from "@/lib/shuttle-utils";
import type { RunnerProfile } from "@/types";
import type { EventShuttleConfig, PickupGuide } from "@/types/shuttle";

interface Props {
  open: boolean;
  eventGuid: string;
  runner: RunnerProfile;
  onClose: () => void;
  onViewMap?: () => void;
}

const defaultPickup = (): PickupGuide => ({
  enabled: true,
  title: "领物须知",
  location: "",
  hours: "",
  items: [],
  mapHint: "",
});

export function PickupGuideSheet({ open, eventGuid, runner, onClose, onViewMap }: Props) {
  const [loading, setLoading] = useState(false);
  const [config, setConfig] = useState<EventShuttleConfig | null>(null);

  useEffect(() => {
    if (!open || !eventGuid) return;
    let cancelled = false;
    setLoading(true);
    fetchEventShuttleConfig(eventGuid)
      .then((data) => {
        if (!cancelled) setConfig(data);
      })
      .catch(() => {
        if (!cancelled) setConfig(null);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [open, eventGuid]);

  const g = config?.pickup ?? defaultPickup();
  const visible = isPickupVisible(config);

  return (
    <SheetModal open={open} title={g.title || "领物须知"} onClose={onClose}>
      {loading && (
        <p className="text-xs text-slate-400 text-center py-8">加载领物须知…</p>
      )}

      {!loading && !visible && (
        <p className="text-xs text-slate-500 text-center py-8">
          组委会暂未发布领物指引，请留意赛事官方通知或咨询现场工作人员。
        </p>
      )}

      {!loading && visible && (
        <>
          <div className="rounded-xl border border-primary/20 bg-primary-surface px-3 py-3 mb-4">
            <p className="text-sm font-bold text-ink">{runner.name}</p>
            <p className="text-lg font-black text-primary-deeper mt-0.5">{runner.bib}</p>
            {g.location?.trim() && (
              <p className="text-xs text-secondary mt-1">{g.location}</p>
            )}
            {g.hours?.trim() && (
              <p className="text-2xs text-primary-dark font-semibold mt-1">{g.hours}</p>
            )}
            {runner.pickupWindow?.trim() && (
              <p className="text-2xs text-slate-600 mt-1">
                领物窗口：{runner.pickupWindow}
              </p>
            )}
          </div>
          {g.items.length > 0 && (
            <ul className="space-y-2.5 mb-4">
              {g.items.map((item) => (
                <li key={item} className="flex gap-2 text-sm text-ink/80 leading-snug">
                  <span className="text-primary shrink-0">·</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          )}
          {g.mapHint?.trim() && (
            <p className="text-xs text-slate-500 mb-4">{g.mapHint}</p>
          )}
          {onViewMap && (
            <button
              type="button"
              onClick={() => {
                onClose();
                onViewMap();
              }}
              className="w-full py-3 rounded-xl bg-primary text-white font-bold text-sm active:bg-primary-dark shadow-primary-sm"
            >
              查看领物点位置（赛道地图）
            </button>
          )}
        </>
      )}
    </SheetModal>
  );
}

// uni-app/src/components/runner/PickupGuideSheet.vue
<template>
  <SheetModal :show="show" :title="title" @close="$emit('close')">
    <view v-if="loading" class="center">加载领物须知…</view>
    <view v-else-if="!visible" class="center muted">
      组委会暂未发布领物指引，请留意赛事官方通知或咨询现场工作人员。
    </view>
    <template v-else>
      <view class="hero">
        <text class="name">{{ runner.name }}</text>
        <text class="bib">{{ runner.bib }}</text>
        <text v-if="guide.location" class="meta">{{ guide.location }}</text>
        <text v-if="guide.hours" class="hours">{{ guide.hours }}</text>
        <text v-if="runner.pickupWindow" class="meta">领物窗口：{{ runner.pickupWindow }}</text>
      </view>
      <view v-for="(item, i) in guide.items" :key="i" class="item">· {{ item }}</view>
      <text v-if="guide.mapHint" class="hint">{{ guide.mapHint }}</text>
      <button v-if="showMapBtn" class="map-btn" @tap="openMap">查看领物点位置（赛道地图）</button>
    </template>
  </SheetModal>
</template>

<script setup>
import { ref, watch, computed } from 'vue'
import SheetModal from './SheetModal.vue'
import { fetchEventShuttleConfig } from '@/utils/runner-api.js'
import { isPickupVisible } from '@/utils/shuttle.js'

const props = defineProps({
  show: Boolean,
  eventGuid: String,
  runner: Object,
})
const emit = defineEmits(['close', 'view-map'])

const loading = ref(false)
const config = ref(null)

watch(
  () => [props.show, props.eventGuid],
  async ([open, guid]) => {
    if (!open || !guid) return
    loading.value = true
    try {
      config.value = await fetchEventShuttleConfig(guid)
    } catch {
      config.value = null
    } finally {
      loading.value = false
    }
  },
)

const guide = computed(
  () =>
    config.value?.pickup ?? {
      title: '领物须知',
      location: '',
      hours: '',
      items: [],
      mapHint: '',
    },
)
const title = computed(() => guide.value.title || '领物须知')
const visible = computed(() => isPickupVisible(config.value))
const showMapBtn = computed(() => visible.value)

function openMap() {
  emit('close')
  emit('view-map')
}
</script>

<style scoped>
.center {
  text-align: center;
  padding: 60rpx 0;
  font-size: 26rpx;
  color: var(--secondary-text, #94a3b8);
}
.muted {
  color: var(--secondary-text, #64748b);
  line-height: 1.5;
  padding: 0 16rpx;
}
.hero {
  background: var(--primary-surface);
  border: 1px solid var(--primary-border, rgba(37, 99, 235, 0.2));
  border-radius: 16rpx;
  padding: 24rpx;
  margin-bottom: 24rpx;
}
.name {
  font-size: 28rpx;
  font-weight: 700;
}
.bib {
  font-size: 40rpx;
  font-weight: 800;
  color: var(--primary-deeper, #1e40af);
  display: block;
}
.meta,
.hours {
  font-size: 24rpx;
  color: var(--secondary-text, #64748b);
  margin-top: 8rpx;
  display: block;
}
.hours {
  color: var(--primary-dark, #1d4ed8);
  font-weight: 600;
}
.item {
  font-size: 28rpx;
  line-height: 1.5;
  margin-bottom: 16rpx;
  color: #334155;
}
.hint {
  font-size: 24rpx;
  color: var(--secondary-text, #64748b);
  margin-bottom: 24rpx;
  display: block;
}
.map-btn {
  width: 100%;
  background: var(--primary);
  color: #fff;
  border-radius: 16rpx;
  font-weight: 700;
}
</style>
