// src/components/modals/RunnerInfoSheet.tsx
import { useEffect, useState } from "react";

import { fetchProfile, mergeProfile } from "@/api/runner-api";

import { SheetModal } from "@/components/modals/SheetModal";

import type { RunnerProfile } from "@/types";



interface Props {

  open: boolean;

  runner: RunnerProfile;

  apiConnected: boolean;

  onClose: () => void;

  onRunnerUpdate?: (runner: RunnerProfile) => void;

}



export function RunnerInfoSheet({

  open,

  runner,

  apiConnected,

  onClose,

  onRunnerUpdate,

}: Props) {

  const [data, setData] = useState(runner);

  const [loading, setLoading] = useState(false);



  useEffect(() => {

    if (!open) return;

    setData(runner);

    if (!apiConnected) return;

    setLoading(true);

    fetchProfile()

      .then((p) => {

        const merged = mergeProfile(runner, p);

        setData(merged);

        onRunnerUpdate?.(merged);

      })

      .catch(() => {})

      .finally(() => setLoading(false));

  }, [open, apiConnected, runner, onRunnerUpdate]);



  const rows = [

    ["参赛号", data.bib],

    ["分区", data.zone],

    ["领物窗口", data.pickupWindow],

    ["检录截止", `${data.zone} ${data.checkInBefore} 前`],

    ["血型", data.bloodType],

    ["紧急联系人", data.emergencyContact],

    ["联系电话", data.emergencyPhone],

  ];



  return (

    <SheetModal open={open} title="我的参赛信息" onClose={onClose}>

      {loading && (

        <p className="text-2xs text-secondary mb-2">正在从服务器同步…</p>

      )}

      <div className="rounded-xl bg-primary-surface border border-primary/20 p-4 mb-4">

        <p className="text-2xs text-secondary">选手</p>

        <p className="text-2xl font-black text-primary-deeper">{data.name}</p>

        <p className="text-3xl font-black mt-1 tracking-wider">{data.bib}</p>

      </div>

      <dl className="space-y-3">

        {rows.map(([k, v]) => (

          <div key={k} className="flex justify-between text-sm border-b border-slate-50 pb-2">

            <dt className="text-slate-500">{k}</dt>

            <dd className="font-semibold text-slate-900 text-right max-w-[60%]">{v}</dd>

          </div>

        ))}

      </dl>

    </SheetModal>

  );

}

// uni-app/src/components/runner/RunnerInfoSheet.vue
<template>
  <SheetModal :show="show" title="我的参赛信息" @close="$emit('close')">
    <text class="sync" :class="{ visible: loading }">正在从服务器同步…</text>
    <view class="hero">
      <text class="label">选手</text>
      <text class="name">{{ data.name }}</text>
      <text class="bib">{{ data.bib }}</text>
    </view>
    <view v-for="(row, i) in displayRows" :key="i" class="row">
      <text class="k">{{ row[0] }}</text>
      <text class="v">{{ row[1] }}</text>
    </view>
  </SheetModal>
</template>

<script setup>
import { ref, watch, computed } from 'vue'
import SheetModal from './SheetModal.vue'
import { fetchProfile, mergeProfile } from '@/utils/runner-api.js'

const props = defineProps({
  show: Boolean,
  runner: Object,
  apiConnected: Boolean,
})
const emit = defineEmits(['close', 'update'])

const data = ref({ ...(props.runner || {}) })
const loading = ref(false)
let wasOpen = false

watch(
  () => [props.show, props.runner],
  async ([open, runner]) => {
    if (!open) {
      wasOpen = false
      loading.value = false
      return
    }
    data.value = { ...runner }
    const justOpened = !wasOpen
    wasOpen = true
    if (!props.apiConnected || !justOpened) return
    loading.value = true
    try {
      const p = await fetchProfile()
      const merged = mergeProfile(runner, p)
      data.value = merged
      emit('update', merged)
    } catch {
      /* ignore */
    } finally {
      loading.value = false
    }
  },
  { deep: true },
)

const displayRows = computed(() => {
  const d = data.value
  return [
    ['参赛号', d.bib],
    ['分区', d.zone],
    ['领物窗口', d.pickupWindow],
    ['检录截止', `${d.zone} ${d.checkInBefore} 前`],
    ['血型', d.bloodType],
    ['紧急联系人', d.emergencyContact],
    ['联系电话', d.emergencyPhone],
  ]
})
</script>

<style scoped>
.sync {
  font-size: 22rpx;
  color: #64748b;
  min-height: 36rpx;
  visibility: hidden;
  margin-bottom: 8rpx;
}
.sync.visible {
  visibility: visible;
}
.hero {
  background: var(--primary-surface);
  border: 1px solid var(--primary-border, rgba(37, 99, 235, 0.2));
  border-radius: 16rpx;
  padding: 24rpx;
  margin-bottom: 24rpx;
}
.label {
  font-size: 22rpx;
  color: #64748b;
}
.name {
  font-size: 40rpx;
  font-weight: 800;
  color: var(--primary-deeper, #1e40af);
  display: block;
}
.bib {
  font-size: 56rpx;
  font-weight: 800;
  letter-spacing: 4rpx;
  display: block;
  margin-top: 8rpx;
}
.row {
  display: flex;
  justify-content: space-between;
  padding: 16rpx 0;
  border-bottom: 1px solid #f1f5f9;
  font-size: 28rpx;
}
.k {
  color: #64748b;
}
.v {
  font-weight: 600;
  max-width: 60%;
  text-align: right;
}
</style>
