// src/components/sos/SosFlowModal.tsx
import { useCallback, useEffect, useRef, useState } from "react";

import {
  fetchSosRescueConfig,
  submitSos,
  submitSosBeacon,
} from "@/api/runner-api";
import { enqueueOfflineSos } from "@/lib/sos-offline-queue";

import { ApiError } from "@/lib/api-client";

import type { RunnerProfile, SosPayload, SosSymptom } from "@/types";



const SYMPTOMS: { id: SosSymptom; label: string }[] = [

  { id: "heart", label: "心脏不适 / 胸闷" },

  { id: "muscle", label: "肌肉拉伤 / 抽筋" },

  { id: "injury", label: "外伤出血 / 跌倒" },

];



const symptomBtnClass =

  "w-full py-5 rounded-xl text-white text-lg font-bold active:opacity-90 shadow-md";

const symptomBtnStyle = {

  background: "linear-gradient(180deg, #ff3b30 0%, #d32f2f 100%)",

};



const AUTO_SEC = 5;



interface Props {

  open: boolean;

  eventGuid: string;

  runner: RunnerProfile;

  apiConnected: boolean;

  onClose: () => void;

  onSubmitted: (payload: SosPayload, serverMessage?: string) => void;

}



export function SosFlowModal({
  open,
  eventGuid,
  runner,
  apiConnected,
  onClose,
  onSubmitted,
}: Props) {

  const [step, setStep] = useState<"gps" | "symptom" | "done">("gps");

  const [countdown, setCountdown] = useState(AUTO_SEC);

  const [gps, setGps] = useState<{ lat: number; lng: number } | null>(null);

  const [env, setEnv] = useState({ battery: 68, signal: "4G 良好" });

  const [submitting, setSubmitting] = useState(false);

  const [rescuePhone, setRescuePhone] = useState("120");

  const [organizerPhone, setOrganizerPhone] = useState<string | null>(null);



  useEffect(() => {
    if (!open || !eventGuid) return;
    fetchSosRescueConfig(eventGuid)
      .then((cfg) => {
        if (cfg.rescuePhone) setRescuePhone(cfg.rescuePhone);
        if (cfg.organizerPhone) setOrganizerPhone(cfg.organizerPhone);
      })
      .catch(() => {
        /* 使用默认 120 */
      });
  }, [open, eventGuid]);

  useEffect(() => {

    if (!open) {

      setStep("gps");

      setCountdown(AUTO_SEC);

      setGps(null);

      return;

    }



    setStep("gps");

    if (navigator.geolocation) {

      navigator.geolocation.getCurrentPosition(

        (pos) => {

          setGps({ lat: pos.coords.latitude, lng: pos.coords.longitude });

          setEnv({

            battery: (navigator as Navigator & { getBattery?: () => Promise<{ level: number }> })

              .getBattery

              ? 68

              : 68,

            signal: "GPS 已定位",

          });

          setStep("symptom");

        },

        () => {

          setGps({ lat: 30.5728, lng: 104.0668 });

          setEnv({ battery: 55, signal: "GPS 不可用·使用近似坐标" });

          setStep("symptom");

        },

        { enableHighAccuracy: true, timeout: 8000 },

      );

    } else {

      const t = window.setTimeout(() => {

        setGps({ lat: 30.5728, lng: 104.0668 });

        setStep("symptom");

      }, 800);

      return () => clearTimeout(t);

    }

  }, [open]);



  const submittedRef = useRef(false);



  const submit = useCallback(

    async (symptom: SosSymptom) => {

      if (submittedRef.current || submitting) return;

      submittedRef.current = true;

      setSubmitting(true);



      const payload: SosPayload = {

        runnerId: runner.id,

        bib: runner.bib,

        name: runner.name,

        bloodType: runner.bloodType,

        emergencyPhone: runner.emergencyPhone,

        gps: gps ?? { lat: 0, lng: 0 },

        battery: env.battery,

        signal: env.signal,

        symptom,

        submittedAt: new Date().toISOString(),

      };



      if (!apiConnected || !navigator.onLine) {
        enqueueOfflineSos(payload);
        setStep("done");
        onSubmitted(
          payload,
          "网络不可用，已本地记录并尝试弱网信标；请立即拨打下方救援电话",
        );
        setSubmitting(false);
        return;
      }

      let serverMessage: string;
      try {
        const res = await submitSos({
          lat: payload.gps.lat,
          lng: payload.gps.lng,
          battery: payload.battery,
          signal: payload.signal,
          symptomKey: symptom,
        });
        serverMessage = res.comfortMessage ?? res.message;
      } catch (e) {
        enqueueOfflineSos(payload);
        try {
          await submitSosBeacon({
            lat: payload.gps.lat,
            lng: payload.gps.lng,
            battery: payload.battery,
          });
        } catch {
          /* ignore */
        }
        submittedRef.current = false;
        setSubmitting(false);
        serverMessage =
          e instanceof ApiError
            ? `${e.message}（已离线缓存，请拨打救援电话）`
            : "SOS 上报失败，已离线缓存，请拨打救援电话";
        onSubmitted(payload, serverMessage);
        return;
      }

      setStep("done");
      onSubmitted(payload, serverMessage);

      setSubmitting(false);

    },

    [gps, env, runner, onSubmitted, apiConnected, submitting],

  );



  useEffect(() => {

    if (!open || step !== "symptom") return;

    submittedRef.current = false;

    setCountdown(AUTO_SEC);

    const iv = setInterval(() => {

      setCountdown((c) => {

        if (c <= 1) {

          clearInterval(iv);

          submit("heart");

          return 0;

        }

        return c - 1;

      });

    }, 1000);

    return () => clearInterval(iv);

  }, [open, step, submit]);



  useEffect(() => {

    if (!open) submittedRef.current = false;

  }, [open]);



  if (!open) return null;



  return (

    <div className="fixed inset-0 z-[60] bg-black/70 flex items-end justify-center max-w-md mx-auto">

      <div className="w-full bg-white rounded-t-2xl p-4 safe-bottom max-h-[90dvh] overflow-y-auto">

        {step === "gps" && (

          <div className="text-center py-8">

            <div className="w-12 h-12 border-4 border-sos border-t-transparent rounded-full animate-spin mx-auto" />

            <p className="mt-4 font-bold text-slate-800">正在获取 GPS 定位…</p>

            <p className="text-xs text-slate-500 mt-1">读取电量与网络信号</p>

          </div>

        )}



        {step === "symptom" && (

          <>

            <div className="flex items-center justify-between mb-3">

              <h3 className="text-lg font-black text-alert">确认伤情</h3>

              <span className="text-xs text-slate-500">{countdown}s 后默认最高级别</span>

            </div>

            <p className="text-xs text-slate-600 mb-3">

              GPS {gps?.lat.toFixed(4)}, {gps?.lng.toFixed(4)} · 电量 {env.battery}% · {env.signal}

            </p>

            <div className="flex gap-2 mb-3">
              <a
                href={`tel:${rescuePhone.replace(/\s/g, "")}`}
                className="flex-1 text-center py-2 rounded-lg bg-red-600 text-white text-xs font-bold"
              >
                拨打 {rescuePhone}
              </a>
              {organizerPhone && (
                <a
                  href={`tel:${organizerPhone.replace(/\s/g, "")}`}
                  className="flex-1 text-center py-2 rounded-lg border border-red-300 text-red-700 text-xs font-bold"
                >
                  组委会
                </a>
              )}
            </div>

            <div className="space-y-3">

              {SYMPTOMS.map((s) => (

                <button

                  key={s.id}

                  type="button"

                  disabled={submitting}

                  onClick={() => submit(s.id)}

                  className={symptomBtnClass}

                  style={symptomBtnStyle}

                >

                  {s.label}

                </button>

              ))}

            </div>

            <button type="button" onClick={onClose} className="w-full mt-4 py-3 text-slate-500 text-sm">

              取消（未发送）

            </button>

          </>

        )}



        {step === "done" && (

          <div className="text-center py-6">

            <p className="text-4xl mb-2">✓</p>

            <p className="text-lg font-bold text-slate-800">救援请求已发送</p>

            <p className="text-sm text-slate-500 mt-2">

              组委会与最近医疗志愿者将收到您的定位

            </p>

            <div className="flex gap-2 mt-4">
              <a
                href={`tel:${rescuePhone.replace(/\s/g, "")}`}
                className="flex-1 text-center py-3 rounded-xl bg-red-600 text-white font-semibold text-sm"
              >
                拨打 {rescuePhone}
              </a>
              {organizerPhone && (
                <a
                  href={`tel:${organizerPhone.replace(/\s/g, "")}`}
                  className="flex-1 text-center py-3 rounded-xl border border-red-300 text-red-700 font-semibold text-sm"
                >
                  组委会
                </a>
              )}
            </div>

            <button

              type="button"

              onClick={onClose}

              className="mt-6 w-full py-3 rounded-xl bg-primary text-white font-semibold active:bg-primary-dark"

            >

              知道了

            </button>

          </div>

        )}

      </div>

    </div>

  );

}

// uni-app/src/components/runner/SosFlowModal.vue
<template>
  <view v-if="show" class="mask">
    <view class="sheet">
      <view v-if="step === 'gps'" class="center">
        <view class="spinner" />
        <text class="bold">正在获取 GPS 定位…</text>
        <text class="muted">读取电量与网络信号</text>
      </view>

      <template v-else-if="step === 'symptom'">
        <view class="row">
          <text class="title-alert">确认伤情</text>
          <text class="muted">{{ countdown }}s 后默认最高级别</text>
        </view>
        <text class="gps-line">
          GPS {{ gpsText }} · 电量 {{ env.battery }}% · {{ env.signal }}
        </text>
        <view class="phones">
          <button class="phone-main" @tap="callPhone(rescuePhone)">拨打 {{ rescuePhone }}</button>
          <button
            v-if="organizerPhone"
            class="phone-sub"
            @tap="callPhone(organizerPhone)"
          >
            组委会
          </button>
        </view>
        <button
          v-for="s in symptoms"
          :key="s.id"
          class="symptom"
          :loading="submitting"
          @tap="doSubmit(s.id)"
        >
          {{ s.label }}
        </button>
        <button class="cancel" @tap="$emit('close')">取消（未发送）</button>
      </template>

      <view v-else class="center">
        <text class="done-icon">✓</text>
        <text class="bold">救援请求已发送</text>
        <text class="muted">组委会与最近医疗志愿者将收到您的定位</text>
        <view class="phones">
          <button class="phone-main" @tap="callPhone(rescuePhone)">拨打 {{ rescuePhone }}</button>
          <button
            v-if="organizerPhone"
            class="phone-sub"
            @tap="callPhone(organizerPhone)"
          >
            组委会
          </button>
        </view>
        <button class="ok" @tap="$emit('close')">知道了</button>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref, watch, computed } from 'vue'
import {
  fetchSosRescueConfig,
  submitSos,
  submitSosBeacon,
} from '@/utils/runner-api.js'
import { enqueueOfflineSos } from '@/utils/sos-offline-queue.js'
import { ApiError } from '@/utils/api.js'

const AUTO_SEC = 5

const props = defineProps({
  show: Boolean,
  eventGuid: String,
  runner: Object,
  apiConnected: Boolean,
})
const emit = defineEmits(['close', 'submitted'])

const symptoms = [
  { id: 'heart', label: '心脏不适 / 胸闷' },
  { id: 'muscle', label: '肌肉拉伤 / 抽筋' },
  { id: 'injury', label: '外伤出血 / 跌倒' },
]

const step = ref('gps')
const countdown = ref(AUTO_SEC)
const gps = ref(null)
const env = ref({ battery: 68, signal: '4G 良好' })
const submitting = ref(false)
const rescuePhone = ref('120')
const organizerPhone = ref(null)
let submitted = false
let countTimer = null

const gpsText = computed(() =>
  gps.value ? `${gps.value.lat.toFixed(4)}, ${gps.value.lng.toFixed(4)}` : '—',
)

watch(
  () => props.show,
  (v) => {
    if (!v) {
      step.value = 'gps'
      countdown.value = AUTO_SEC
      gps.value = null
      submitted = false
      if (countTimer) clearInterval(countTimer)
      return
    }
    step.value = 'gps'
    submitted = false
    if (props.eventGuid) {
      fetchSosRescueConfig(props.eventGuid)
        .then((cfg) => {
          if (cfg.rescuePhone) rescuePhone.value = cfg.rescuePhone
          if (cfg.organizerPhone) organizerPhone.value = cfg.organizerPhone
        })
        .catch(() => {})
    }
    uni.getLocation({
      type: 'gcj02',
      success(res) {
        gps.value = { lat: res.latitude, lng: res.longitude }
        env.value = { battery: 68, signal: 'GPS 已定位' }
        step.value = 'symptom'
      },
      fail() {
        gps.value = { lat: 30.5728, lng: 104.0668 }
        env.value = { battery: 55, signal: 'GPS 不可用·使用近似坐标' }
        step.value = 'symptom'
      },
    })
  },
)

watch(
  () => [props.show, step.value],
  () => {
    if (countTimer) clearInterval(countTimer)
    if (!props.show || step.value !== 'symptom') return
    submitted = false
    countdown.value = AUTO_SEC
    countTimer = setInterval(() => {
      countdown.value -= 1
      if (countdown.value <= 0) {
        clearInterval(countTimer)
        doSubmit('heart')
      }
    }, 1000)
  },
)

function callPhone(num) {
  uni.makePhoneCall({ phoneNumber: String(num).replace(/\s/g, '') })
}

async function doSubmit(symptomKey) {
  if (submitted || submitting.value) return
  submitted = true
  submitting.value = true

  const payload = {
    runnerId: props.runner?.id,
    bib: props.runner?.bib,
    name: props.runner?.name,
    gps: gps.value ?? { lat: 0, lng: 0 },
    battery: env.value.battery,
    signal: env.value.signal,
    symptomKey,
    submittedAt: new Date().toISOString(),
  }

  if (!props.apiConnected) {
    enqueueOfflineSos(payload)
    step.value = 'done'
    emit('submitted', '网络不可用，已本地记录；请立即拨打救援电话')
    submitting.value = false
    return
  }

  try {
    const res = await submitSos({
      lat: payload.gps.lat,
      lng: payload.gps.lng,
      battery: payload.battery,
      signal: payload.signal,
      symptomKey,
    })
    step.value = 'done'
    emit('submitted', res.comfortMessage ?? res.message)
  } catch (e) {
    enqueueOfflineSos(payload)
    try {
      await submitSosBeacon({
        lat: payload.gps.lat,
        lng: payload.gps.lng,
        battery: payload.battery,
      })
    } catch {
      /* ignore */
    }
    submitted = false
    const msg =
      e instanceof ApiError
        ? `${e.message}（已离线缓存，请拨打救援电话）`
        : 'SOS 上报失败，已离线缓存，请拨打救援电话'
    emit('submitted', msg)
  } finally {
    submitting.value = false
  }
}
</script>

<style scoped>
.mask {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.7);
  z-index: 300;
  display: flex;
  align-items: flex-end;
}
.sheet {
  width: 100%;
  background: #fff;
  border-radius: 24rpx 24rpx 0 0;
  padding: 40rpx 32rpx calc(40rpx + env(safe-area-inset-bottom));
  max-height: 90vh;
  overflow-y: auto;
}
.center {
  text-align: center;
  padding: 60rpx 0;
}
.spinner {
  width: 80rpx;
  height: 80rpx;
  border: 6rpx solid #fecaca;
  border-top-color: #dc2626;
  border-radius: 50%;
  margin: 0 auto 24rpx;
  animation: spin 1s linear infinite;
}
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
.bold {
  font-size: 32rpx;
  font-weight: 700;
  display: block;
}
.muted {
  font-size: 24rpx;
  color: #64748b;
  margin-top: 8rpx;
  display: block;
}
.row {
  display: flex;
  justify-content: space-between;
  margin-bottom: 16rpx;
}
.title-alert {
  font-size: 34rpx;
  font-weight: 800;
  color: #dc2626;
}
.gps-line {
  font-size: 24rpx;
  color: #475569;
  margin-bottom: 20rpx;
  display: block;
}
.phones {
  display: flex;
  gap: 16rpx;
  margin-bottom: 24rpx;
}
.phone-main {
  flex: 1;
  background: #dc2626;
  color: #fff;
  font-size: 24rpx;
  border-radius: 12rpx;
}
.phone-sub {
  flex: 1;
  border: 1px solid #fecaca;
  color: #b91c1c;
  font-size: 24rpx;
  border-radius: 12rpx;
  background: #fff;
}
.symptom {
  width: 100%;
  margin-bottom: 20rpx;
  background: linear-gradient(180deg, #ff3b30, #d32f2f);
  color: #fff;
  font-size: 32rpx;
  font-weight: 700;
  border-radius: 16rpx;
}
.cancel {
  width: 100%;
  margin-top: 16rpx;
  color: #64748b;
  background: transparent;
  font-size: 28rpx;
}
.done-icon {
  font-size: 80rpx;
  display: block;
  margin-bottom: 16rpx;
}
.ok {
  margin-top: 32rpx;
  width: 100%;
  background: var(--primary);
  color: #fff;
  border-radius: 16rpx;
}
</style>
